version: "3.8"

services:
  backend:
    build:
      context: ./Backend
    env_file:
      - .env
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./Brontend
    env_file:
      - .env
    ports:
      - "3000:80"
